##	Each new term in the Fibonacci sequence is generated by adding the previous two
##	terms. By starting with 1 and 2, the first 10 terms will be:
##		1, 2, 3, 5, 8, 13, 21, 34, 55, 89.....
##
##	By considering the terms in the Fibonacci sequence whose values do not exceed four
##	million, find the sum of the even-valued terms.

## Previous two terms
term1 = 1
term2 = 2

i = 0
bound = 4e+6

## Start the total at 2
total = 2

while i < bound:
	i = term1 + term2
	if i%2 == 0:
		total += i

	term1 = term2
	term2 = i

print(total)
